name: Build Fabric Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Use Gradle 8.6
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.6

    - name: Give gradlew permission
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Clean build folders
      run: ./gradlew clean

